spring:
  application:
    name: pacman_gateway
  data:
    mongodb:
      uri: mongodb://192.168.99.100:27017/pacman
      service: mongo-db
server:
  port: 8080

logging:
  level:
    pacman: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
pacman:
  player_manager:
    uri: localhost
    port: 9090
    url: ${pacman.player_manager.uri}:${pacman.player_manager.port}
  session_manager:
    uri: localhost
    port: 8081
    url: ${pacman.session_manager.uri}:${pacman.session_manager.port}
  game_manager:
    uri: localhost
    port: 8085
    url: ${pacman.game_manager.uri}:${pacman.game_manager.port}
  gateway:
    uri: localhost
    port: 8080
    url: ${pacman.gateway.uri}:${pacman.gateway.port}